services:
  backend:
    image: python:3.12-slim
    container_name: calry_backend
    working_dir: /app
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/calry_db
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt
      && alembic upgrade head
      && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine # Versione stabile e leggera
    container_name: calry_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calry_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calry_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: calry_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    
volumes:
  postgres_data: # Mantiene i dati persistenti anche se spegni il container
