"""update_ai_pipeline_fields

Revision ID: 72a75ccb657c
Revises: initial_setup
Create Date: 2026-05-28 22:01:22.306369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a75ccb657c'
down_revision: Union[str, None] = 'initial_setup'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_inference_logs', sa.Column('provider', sa.String(length=50), nullable=False, server_default='openrouter'))
    op.add_column('ai_inference_logs', sa.Column('prompt_version', sa.String(length=100), nullable=False, server_default='unknown'))
    op.add_column('ai_inference_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('meal_items', sa.Column('quantity_estimate', sa.String(length=100), nullable=True))
    op.add_column('meal_items', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('meals', sa.Column('audio_url', sa.String(length=1024), nullable=True))
    op.add_column('meals', sa.Column('meal_name', sa.String(length=255), nullable=True))
    op.add_column('meals', sa.Column('estimated_min_calories', sa.Integer(), nullable=True))
    op.add_column('meals', sa.Column('estimated_max_calories', sa.Integer(), nullable=True))
    op.add_column('meals', sa.Column('correction_delta', sa.Integer(), nullable=True))
    op.add_column('meals', sa.Column('correction_percent', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('needs_clarification', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('meals', sa.Column('clarifying_question', sa.Text(), nullable=True))
    op.add_column('meals', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meals', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.alter_column('meals', 'ai_confidence',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meals', 'ai_confidence',
               existing_type=sa.String(length=50),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_column('meals', 'updated_at')
    op.drop_column('meals', 'confirmed_at')
    op.drop_column('meals', 'clarifying_question')
    op.drop_column('meals', 'needs_clarification')
    op.drop_column('meals', 'correction_percent')
    op.drop_column('meals', 'correction_delta')
    op.drop_column('meals', 'estimated_max_calories')
    op.drop_column('meals', 'estimated_min_calories')
    op.drop_column('meals', 'meal_name')
    op.drop_column('meals', 'audio_url')
    op.drop_column('meal_items', 'created_at')
    op.drop_column('meal_items', 'quantity_estimate')
    op.drop_column('ai_inference_logs', 'error_message')
    op.drop_column('ai_inference_logs', 'prompt_version')
    op.drop_column('ai_inference_logs', 'provider')
    # ### end Alembic commands ###
