"""Create a RevenueCat-backed free-access code without storing its plaintext.

Usage:
    python scripts/create_promo_code.py
    python scripts/create_promo_code.py --code CALRY-FOUNDERS-2026 --max-redemptions 25
    python scripts/create_promo_code.py --valid-days 30 --max-redemptions 100

The plaintext code is printed once. Store it in a password manager; the
database contains only an HMAC digest and a short non-secret hint.
"""

from __future__ import annotations

import argparse
import asyncio
import datetime as dt
import secrets
import sys
from pathlib import Path

from sqlalchemy import select

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.core.config import settings  # noqa: E402
from app.db.session import SessionLocal  # noqa: E402
from app.models.promo_code import PromoCode  # noqa: E402
from app.services.promo_code_service import (  # noqa: E402
    normalize_promo_code,
    promo_code_digest,
    promo_code_hint,
)


def _generated_code() -> str:
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    token = "".join(secrets.choice(alphabet) for _ in range(16))
    return f"CALRY-{token[:4]}-{token[4:8]}-{token[8:12]}-{token[12:]}"


async def create_code(args: argparse.Namespace) -> None:
    pepper = settings.PROMO_CODE_PEPPER
    if not pepper:
        raise SystemExit("PROMO_CODE_PEPPER must be configured before creating codes.")

    plaintext = args.code or _generated_code()
    normalized = normalize_promo_code(plaintext)
    if len(normalized) < 8 or len(normalized) > 64:
        raise SystemExit("Code must contain between 8 and 64 letters/digits.")

    digest = promo_code_digest(plaintext, pepper)
    valid_until = None
    if args.valid_days is not None:
        valid_until = dt.datetime.now(dt.UTC) + dt.timedelta(days=args.valid_days)

    async with SessionLocal() as db:
        exists = (await db.execute(select(PromoCode.id).where(PromoCode.code_digest == digest))).scalar_one_or_none()
        if exists is not None:
            raise SystemExit("A code with this value already exists.")

        db.add(
            PromoCode(
                code_digest=digest,
                code_hint=promo_code_hint(plaintext),
                kind="free_access",
                grant_duration="lifetime",
                max_redemptions=args.max_redemptions,
                valid_until=valid_until,
            )
        )
        await db.commit()

    print("Free-access code created. This plaintext is shown only now:")
    print(plaintext)
    print(f"Hint stored in database: {promo_code_hint(plaintext)}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a hashed Calry Pro free-access code.")
    parser.add_argument("--code", help="Optional plaintext code; a secure random code is generated by default.")
    parser.add_argument("--max-redemptions", type=int, default=1)
    parser.add_argument("--valid-days", type=int)
    args = parser.parse_args()
    if args.max_redemptions is not None and args.max_redemptions < 1:
        parser.error("--max-redemptions must be at least 1")
    if args.valid_days is not None and args.valid_days < 1:
        parser.error("--valid-days must be at least 1")
    asyncio.run(create_code(args))


if __name__ == "__main__":
    main()
